version: '3'
services:
  # PHP Service
  app:
    build:
      args:
        user: ec2-user
        uid: 1000
      context: .
      dockerfile: docker/Dockerfile
    image: php-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      #- ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf

    networks:
      - internet

    # command:
    #   - /bin/sh
    #   - -c
    # #   - supervisord -c /var/www/docker/supervisor/supervisord.conf
    #   - php /var/www/artisan optimize
    #   - supervisorctl start all
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # ports:
    #   - "9001:9000"

  # Nginx Service
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx-server
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./:/var/www
      # - ./docker/nginx_prod:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      APP_ENV: "${APP_ENV}"
      APP_URL: "${APP_URL_BASE}"
    networks:
      - internet

    # external_links:
    #   - app
    # links:
    #   - app
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/html --email info@ashrafulfrioz.com --agree-tos --no-eff-email --staging  -d milan.aalpphotos.ashrafulfiroz.com


# Network
networks:
  internet:


# Data Volumes
volumes:
  dbdata:


