version: '3'
services:

  # PHP Service
  app:
    build:
      args:
        user: ec2-user
        uid: 1000
      context: .
      dockerfile: docker/Dockerfile
    image: php-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      #- ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    networks:
      - internet

    # command:
    #   - /bin/sh
    #   - -c
    # #   - supervisord -c /var/www/docker/supervisor/supervisord.conf
    #   - php /var/www/artisan optimize
    #   - supervisorctl start all
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # ports:
    #   - "9001:9000"

  # Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx_local:/etc/nginx/conf.d
      # - /etc/ssl/certs/oto-repair.crt:/etc/ssl/certs/ssl.crt
      # - /etc/ssl/private/oto-repair.key:/etc/ssl/private/ssl-private.key
    networks:
      - internet

    external_links:
      - app
    links:
      - app
    depends_on:
      - app


# Network
networks:
  internet:


# Data Volumes
volumes:
  dbdata:

