version: '3'
services:
  # PHP Service
  app:
    build:
      args:
        user: ec2-user
        uid: 1000
      context: .
      dockerfile: docker/php/Dockerfile
    image: php-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker/php/my.ini:/usr/local/etc/php/conf.d/my.ini

    networks:
      - internet
    extra_hosts:
      - "host.docker.internal:host-gateway"


  # Nginx Service
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx-server
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./:/var/www
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      APP_ENV: "${APP_ENV}"
      APP_URL: "${APP_URL_BASE}"
    networks:
      - internet
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# Network
networks:
  internet:



